# Generated by Django 5.1.7 on 2025-03-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('adjustment_type', models.CharField(max_length=30)),
                ('value', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
    ]
